# Generated by Django 3.2.7 on 2021-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome:')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail:')),
                ('pais', models.CharField(max_length=255, verbose_name='País:')),
                ('estado', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255, verbose_name='Município:')),
                ('cep', models.CharField(max_length=255, verbose_name='CEP:')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua:')),
                ('numero', models.CharField(max_length=255, verbose_name='Número:')),
                ('Complemento', models.CharField(max_length=255, verbose_name='Complemento:')),
                ('cpf', models.CharField(max_length=255, verbose_name='CPF:')),
                ('pis', models.CharField(max_length=255, verbose_name='PIS:')),
            ],
        ),
    ]
