# Generated by Django 3.2.7 on 2021-09-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Complemento',
            new_name='complemento',
        ),
    ]
