# Generated by Django 3.2.7 on 2021-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_rename_complemento_usuario_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(max_length=255, null=True, verbose_name='Complemento:'),
        ),
    ]
