# Generated by Django 3.2.7 on 2021-09-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_usuario_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=255, unique=True, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='e-mail:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pis',
            field=models.CharField(max_length=255, unique=True, verbose_name='PIS:'),
        ),
    ]
