# Generated by Django 3.2.7 on 2021-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20210919_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pis',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='PIS:'),
        ),
    ]
